In [1]:
import tensorflow as tf

2025-04-13 00:14:33.584539: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-13 00:14:33.609188: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-04-13 00:14:33.609207: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-04-13 00:14:33.609833: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-13 00:14:33.614382: I tensorflow/core/platform/cpu_feature_guar

In [2]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dense(10),
])

2025-04-13 00:41:16.286000: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-04-13 00:41:16.289703: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-04-13 00:41:16.289814: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [3]:
[net.layers[i].get_weights() for i in range(len(net.layers))]

[[], []]

In [4]:
X = tf.random.normal((2, 20))

In [5]:
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.6402305 , -0.27260637,  0.15306698, -0.18914965,  0.06485242,
        -0.06347373, -0.17001495,  0.26808476,  0.18847601,  0.23469308],
       [-0.47660643, -0.07376152,  0.4777261 ,  0.26787046, -0.16207838,
        -0.09762211,  0.19017561,  0.02886812,  0.27419716,  0.5081141 ]],
      dtype=float32)>

In [6]:
[w.shape for w in net.get_weights()]

[(20, 256), (256,), (256, 10), (10,)]

In [1]:
import torch
from torch import nn


In [2]:
net = nn.Sequential(
    nn.LazyLinear(256),
    nn.ReLU(),
    nn.LazyLinear(10)
)


/opt/conda/lib/python3.10/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
print(net[0].weight)
print(net)

<UninitializedParameter>
Sequential(
  (0): LazyLinear(in_features=0, out_features=256, bias=True)
  (1): ReLU()
  (2): LazyLinear(in_features=0, out_features=10, bias=True)
)


In [6]:
X = torch.randn(2, 20)

In [7]:
net(X)

tensor([[-0.3459,  0.3547, -0.3784, -0.4250, -0.0876,  0.0683,  0.1701, -0.4519,
          0.3722, -0.2456],
        [ 0.3486, -0.2596, -0.1820,  0.1065,  0.2683, -0.0559, -0.1469, -0.2856,
          0.5988, -0.4999]], grad_fn=<AddmmBackward0>)

In [8]:
print(net[0].weight)
print(net)

Parameter containing:
tensor([[-0.1361,  0.1619,  0.0454,  ...,  0.2100, -0.1745, -0.1409],
        [-0.1721, -0.2194, -0.1876,  ...,  0.1305,  0.1887, -0.0530],
        [ 0.1208, -0.0137, -0.1663,  ...,  0.1913, -0.1079, -0.0385],
        ...,
        [ 0.1320,  0.1990, -0.1084,  ...,  0.1080, -0.2080,  0.2024],
        [ 0.0517,  0.2034,  0.0578,  ...,  0.0534,  0.1474,  0.1735],
        [ 0.1095, -0.0285,  0.0152,  ...,  0.2126,  0.1117, -0.0186]],
       requires_grad=True)
Sequential(
  (0): Linear(in_features=20, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=10, bias=True)
)
