In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer.forward(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer(),
)

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear)
    

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.1415, -1.6179, -0.7710],
        [ 0.4436,  1.4212, -0.7939],
        [-0.2853,  0.2798,  1.0040],
        [ 1.1088,  0.3117,  1.0794],
        [ 1.1903, -0.3716,  1.6366]], requires_grad=True)

In [10]:
linear.bias

Parameter containing:
tensor([-0.9910, -0.1044,  0.7293], requires_grad=True)

In [11]:
linear(torch.rand(2, 5))

tensor([[0.9018, 0.0155, 1.9072],
        [1.2149, 0.0000, 1.2835]], grad_fn=<ReluBackward0>)

In [12]:
net = nn.Sequential(
    MyLinear(64, 8),
    MyLinear(8, 1)
)
net(torch.rand(2, 64))

tensor([[0.],
        [0.]], grad_fn=<ReluBackward0>)